# Generated by Django 4.0.2 on 2022-02-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_alter_raidevent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidBosses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='raidinstance',
            name='boss',
        ),
        migrations.AddField(
            model_name='raidinstance',
            name='bosses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.raidbosses'),
            preserve_default=False,
        ),
    ]
