# Generated by Django 4.0.2 on 2022-02-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BossPerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.boss')),
            ],
        ),
        migrations.CreateModel(
            name='LateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_late', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('rank', models.IntegerField(choices=[(0, 'GM'), (1, 'Officer'), (2, 'Officer Alt'), (3, 'Raider'), (4, 'Second Main'), (5, 'Trial')])),
                ('character_id', models.IntegerField(unique=True)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('playable_class', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('socialaccount.socialaccount',),
        ),
        migrations.CreateModel(
            name='RaidEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Raid', max_length=30)),
                ('date', models.DateField(unique=True)),
                ('bosses', models.ManyToManyField(through='core.BossPerEvent', to='core.Boss')),
                ('late', models.ManyToManyField(through='core.LateUser', to='core.MyUser')),
                ('roster', models.ManyToManyField(blank=True, default=True, related_name='roster', to='core.Roster')),
            ],
        ),
        migrations.AddField(
            model_name='lateuser',
            name='raid_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.raidevent'),
        ),
        migrations.AddField(
            model_name='lateuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.myuser'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='healer',
            field=models.ManyToManyField(blank=True, related_name='rel_healer', to='core.Roster'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='mdps',
            field=models.ManyToManyField(blank=True, related_name='rel_mdps', to='core.Roster'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='raid_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.raidevent'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='rdps',
            field=models.ManyToManyField(blank=True, related_name='rel_rdps', to='core.Roster'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='tank',
            field=models.ManyToManyField(blank=True, related_name='rel_tank', to='core.Roster'),
        ),
    ]
