# Generated by Django 4.0.2 on 2022-02-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BossPerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.boss')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('character_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('playable_class', models.CharField(blank=True, max_length=30, null=True)),
                ('rank', models.IntegerField(choices=[(0, 'GM'), (1, 'Officer'), (2, 'Officer Alt'), (3, 'Raider'), (4, 'Second Main'), (5, 'Trial')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('rank', models.IntegerField(choices=[(0, 'GM'), (1, 'Officer'), (2, 'Officer Alt'), (3, 'Raider'), (4, 'Second Main'), (5, 'Trial')])),
                ('character_id', models.IntegerField(unique=True)),
                ('playable_class', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaidInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('bosses', models.ManyToManyField(blank=True, to='core.BossPerEvent')),
            ],
        ),
        migrations.CreateModel(
            name='RaidEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Raid', max_length=30)),
                ('date', models.DateField(unique=True)),
                ('bosses', models.ManyToManyField(through='core.BossPerEvent', to='core.Boss')),
                ('roster', models.ManyToManyField(blank=True, default=True, to='core.Roster')),
            ],
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='inherited_roster',
            field=models.ManyToManyField(blank=True, to='core.Roster'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='raid_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.raidevent'),
        ),
    ]
