# Generated by Django 4.0.2 on 2022-02-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaidInstance',
        ),
    ]
