# Generated by Django 4.0.2 on 2022-02-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_raidinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossperevent',
            name='healer',
            field=models.ManyToManyField(blank=True, related_name='rel_healer', to='core.Roster'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='mdps',
            field=models.ManyToManyField(blank=True, related_name='rel_mdps', to='core.Roster'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='rdps',
            field=models.ManyToManyField(blank=True, related_name='rel_rdps', to='core.Roster'),
        ),
        migrations.AddField(
            model_name='bossperevent',
            name='tank',
            field=models.ManyToManyField(blank=True, related_name='rel_tank', to='core.Roster'),
        ),
    ]
