# Generated by Django 4.0.1 on 2022-01-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
