# Generated by Django 4.0.2 on 2022-02-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bossperevent_healer_bossperevent_mdps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bossperevent',
            name='inherited_roster',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='role',
        ),
    ]
