# Generated by Django 4.0.1 on 2022-01-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_player_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
