# Generated by Django 4.0.2 on 2022-02-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bossperevent_inherited_roster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='account_id',
            field=models.IntegerField(null=True),
        ),
    ]
