# Generated by Django 4.0.2 on 2022-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roster_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
