# Generated by Django 4.0.2 on 2022-02-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_roster_account_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUser',
        ),
    ]
