# Generated by Django 4.0.1 on 2022-01-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_player_currentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='rank',
            field=models.IntegerField(choices=[(0, 'GM'), (1, 'Officer'), (2, 'Officer Alt'), (3, 'Raider'), (4, 'Second Main'), (5, 'Trial')]),
        ),
        migrations.AlterField(
            model_name='roster',
            name='rank',
            field=models.IntegerField(choices=[(0, 'GM'), (1, 'Officer'), (2, 'Officer Alt'), (3, 'Raider'), (4, 'Second Main'), (5, 'Trial')]),
        ),
    ]
