# Generated by Django 4.0.2 on 2022-02-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_roster_character_id_raidevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='character_id',
            field=models.IntegerField(),
        ),
    ]
