# Generated by Django 4.0.2 on 2022-02-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_currentuser_character_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='raidevent',
            name='roster',
        ),
        migrations.AddField(
            model_name='raidevent',
            name='roster',
            field=models.ManyToManyField(to='core.Roster'),
        ),
    ]
