# Generated by Django 4.0.2 on 2022-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_raidinstance_remove_raidevent_roster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidevent',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='character_id',
            field=models.IntegerField(unique=True),
        ),
    ]
