# Generated by Django 4.0.2 on 2022-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_raidevent_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='in_raid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='raidevent',
            name='roster',
            field=models.ManyToManyField(blank=True, to='core.Roster'),
        ),
    ]
