# Generated by Django 4.0.2 on 2022-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_roster_in_raid_alter_raidevent_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidevent',
            name='sign_off',
        ),
        migrations.AddField(
            model_name='raidevent',
            name='sign_off',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
