# Generated by Django 4.0.2 on 2022-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_raidevent_sign_off_raidevent_sign_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidevent',
            name='sign_off',
            field=models.CharField(blank=True, default='placeholder', max_length=30),
        ),
    ]
