# Generated by Django 4.0.2 on 2022-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_raidevent_sign_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidevent',
            name='sign_off',
        ),
        migrations.AddField(
            model_name='raidevent',
            name='sign_off',
            field=models.ManyToManyField(blank=True, to='core.CurrentUser'),
        ),
    ]
