# Generated by Django 4.0.2 on 2022-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_raidevent_sign_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidevent',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
