# Generated by Django 4.0.2 on 2022-02-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_raidinstance_boss_alter_raidinstance_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidBosses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='raidinstance',
            name='boss',
        ),
        migrations.AddField(
            model_name='raidinstance',
            name='bosses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.raidbosses'),
        ),
    ]
