# Generated by Django 4.0.2 on 2022-02-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_currentuser_raid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentuser',
            name='raid_status',
        ),
    ]
