# Generated by Django 4.0.2 on 2022-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_raidbosses_remove_raidinstance_boss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidinstance',
            name='bosses',
        ),
        migrations.AddField(
            model_name='raidinstance',
            name='bosses',
            field=models.ManyToManyField(blank=True, to='core.RaidBosses'),
        ),
    ]
