# Generated by Django 4.0.2 on 2022-02-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_currentuser_playable_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='in_raid',
        ),
    ]
