# Generated by Django 4.0.2 on 2022-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_roster_in_raid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='playable_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
