# Generated by Django 4.0.1 on 2022-01-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('character_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
