# Generated by Django 4.0.1 on 2022-01-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.CharField(default='main', max_length=10),
            preserve_default=False,
        ),
    ]
