# Generated by Django 4.0.1 on 2022-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(choices=[(0, 'GM'), (1, 'Officer'), (2, 'Officer Alt'), (3, 'Raider'), (4, 'Second Main'), (5, 'Alt')]),
        ),
    ]
