# Generated by Django 4.0.1 on 2022-01-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
