# Generated by Django 4.0.2 on 2022-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_alter_currentuser_character_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='character_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='currentuser',
            name='rank',
            field=models.IntegerField(choices=[(0, 'GM'), (1, 'Officer'), (2, 'Officer Alt'), (3, 'Raider'), (4, 'Second Main'), (5, 'Trial')], null=True),
        ),
    ]
