# Generated by Django 4.0.2 on 2022-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_raidevent_name_alter_roster_character_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidevent',
            name='name',
            field=models.CharField(default='Placeholder', max_length=30),
        ),
    ]
