# Generated by Django 4.0.2 on 2022-02-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_alter_raidevent_name_alter_raidevent_sign_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidevent',
            name='sign_off',
            field=models.ManyToManyField(blank=True, to='players.CurrentUser'),
        ),
    ]
