# Generated by Django 4.0.2 on 2022-02-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_alter_raidevent_sign_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidevent',
            name='roster',
        ),
    ]
