# Generated by Django 4.0.2 on 2022-02-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_remove_raidevent_sign_off_raidevent_sign_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidevent',
            name='roster',
        ),
        migrations.AddField(
            model_name='raidevent',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.roster'),
        ),
    ]
