# Generated by Django 4.0.2 on 2022-02-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_remove_raidevent_roster_raidevent_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidevent',
            name='roster',
        ),
        migrations.AddField(
            model_name='raidevent',
            name='roster',
            field=models.ManyToManyField(blank=True, to='players.Roster'),
        ),
    ]
