# Generated by Django 4.0.2 on 2022-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_remove_raidevent_roster_raidevent_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidevent',
            name='roster',
            field=models.ManyToManyField(blank=True, default=True, to='players.Roster'),
        ),
    ]
