# Generated by Django 4.0.2 on 2022-02-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_alter_raidevent_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidevent',
            name='sign_off',
        ),
    ]
