# Generated by Django 4.0.2 on 2022-02-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_alter_raidevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentuser',
            name='raid_status',
            field=models.IntegerField(default=0),
        ),
    ]
