# Generated by Django 4.0.2 on 2022-02-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_remove_currentuser_raid_status'),
        ('players', '0037_remove_raidinstance_bosses_raidinstance_bosses'),
    ]

    operations = [
    ]
