# Generated by Django 4.0.2 on 2022-02-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_merge_20220205_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentuser',
            name='playable_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
